# Generated by Django 4.0.5 on 2022-07-04 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familia',
            old_name='apellido',
            new_name='Apellido',
        ),
        migrations.RenameField(
            model_name='familia',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='familia',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='familia',
            old_name='profesion',
            new_name='Profesion',
        ),
    ]
